language: python
python:
  - "3.9"

branches:
  only:
    - main

before_install:
  - 'echo hi'

install:
  - sudo apt-get install tree
  - gem install asciidoctor
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py
  - pip3 install Pygments
  - pip3 install -r scripts/requirements.txt
  - export PATH=~/.local/bin:$PATH
  - rm -rf public || exit 0

script:
  - ./bin/hugo --buildFuture --verbose
  - cd public
  - touch .nojekyll
  - echo "presidioworkshops.com" > CNAME
  - tree workshops
  - tree events
  - cd ..
  - pwd

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  verbose: true
  on:
    branch: main
